Fix conflicting types for 'off_t'
-[51007]% C make
make -f objs/Makefile
make[1]: Entering directory `/home/khayashi/work/nginx/nginx-work'
x86_64-w64-mingw32-gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/win32 -I objs \
                          -o objs/src/core/nginx.o \
                             src/core/nginx.c
In file included from src/core/ngx_config.h:38:0,
                 from src/core/nginx.c:8:
src/os/win32/ngx_win32_config.h:138:29: error: conflicting types for 'off_t'
/usr/lib/gcc/x86_64-w64-mingw32/4.6/../../../../x86_64-w64-mingw32/include/_mingw_off_t.h:26:17: note: previous declaration of 'off_t' was here