Fix redefined intptr_t/uintptr_t error
-[51007]% C make
make -f objs/Makefile
make[1]: Entering directory `/home/khayashi/work/nginx/nginx-work'
x86_64-w64-mingw32-gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/win32 -I objs \
                          -o objs/src/core/nginx.o \
                             src/core/nginx.c
In file included from src/core/ngx_config.h:38:0,
                 from src/core/nginx.c:8:
src/os/win32/ngx_win32_config.h:130:29: error: conflicting types for 'intptr_t'
/usr/lib/gcc/x86_64-w64-mingw32/4.6/../../../../x86_64-w64-mingw32/include/_mingw.h:406:35: note: previous declaration of 'intptr_t' was here
src/os/win32/ngx_win32_config.h:131:29: error: conflicting types for 'uintptr_t'
/usr/lib/gcc/x86_64-w64-mingw32/4.6/../../../../x86_64-w64-mingw32/include/_mingw.h:419:44: note: previous declaration of 'uintptr_t' was here