Fix conflictiong types for 'ssize_t'
-[51026]% C make
make -f objs/Makefile
make[1]: Entering directory `/home/khayashi/work/nginx/nginx-work'
x86_64-w64-mingw32-gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/win32 -I objs \
                          -o objs/src/core/nginx.o \
                             src/core/nginx.c
In file included from src/core/ngx_config.h:38:0,
                 from src/core/nginx.c:8:
src/os/win32/ngx_win32_config.h:145:29: error: conflicting types for 'ssize_t'
/usr/lib/gcc/x86_64-w64-mingw32/4.6/../../../../x86_64-w64-mingw32/include/_mingw.h:394:35: note: previous declaration of 'ssize_t' was here
make[1]: *** [objs/src/core/nginx.o] Error 1
make[1]: Leaving directory `/home/khayashi/work/nginx/nginx-work'
make: *** [build] Error 2